### PR TITLE
[QDP] Fix DLPack device_id hardcoding

### LINKED ISSUE #744: [QDP] Fix DLPack device_id hardcoding
### Summary
GpuStateVector::to_dlpack() hardcodes device_id: 0, breaking multi-GPU scenarios and making device_id metadata incorrect.

### PR DESCRIPTION
**Pull request by rich7420**
### Purpose of PR

This PR fixed the hardcoded device_id bug — instead of always saying device 0, it now grabs the actual device ID from the CudaDevice when allocating memory. The Python bindings now read the device_id straight from the DLPack tensor metadata, so multi-GPU setups work correctly without any manual device tracking.

### Related Issues or PRs

Closes #744 

### Changes Made

- [ ] Bug fix
- [ ] New feature
- [x] Refactoring
- [ ] Documentation
- [ ] Test
- [ ] CI/CD pipeline
- [ ] Other

### Breaking Changes

- [ ] Yes
- [x] No

### Checklist

- [x] Added or updated unit tests for all changes
- [ ] Added or updated documentation for all changes
- [x] Successfully built and ran all unit tests or manual tests locally
- [ ] PR title follows "MAHOUT-XXX: Brief Description" format (if related to an issue)
- [ ] Code follows ASF guidelines

### CODE REVIEW

**Comment by rich7420** [comment]
With this PR, we don’t do anything special with that env. We just use CUDA’s device index, so if you run CUDA_VISIBLE_DEVICES=1 python some_script.py, the engine just sees one device as 0. The DLPack metadata will also report (kDLCUDA, 0), which matches what PyTorch and other libraries in the same process see.
plz correct me if I'm wrong.

File: qdp/qdp-python/src/lib.rs [hunk 1]
```diff
@@ -94,8 +94,22 @@ impl QuantumTensor {
...
+        if self.ptr.is_null() {
+            return Err(PyRuntimeError::new_err("Invalid DLPack tensor pointer"));
+        }
+
+        unsafe {
+            // Read device_id from DLPack tensor metadata
+            // DLDeviceType::kDLCUDA = 2 (from dlpack.h)
+            let tensor = &(*self.ptr).dl_tensor;
+            // device_type is an enum, convert to integer
+            // kDLCUDA = 2, kDLCPU = 1
```
Comment (machichima) [inline qdp/qdp-python/src/lib.rs:104]:
```suggestion
            // kDLCUDA = 2, kDLCPU = 1
            // Ref: https://github.com/dmlc/dlpack/blob/6ea9b3eb64c881f614cd4537f95f0e125a35555c/include/dlpack/dlpack.h#L76-L80
```
nit: add ref for enum definition

File: qdp/qdp-python/src/lib.rs [hunk 2]
```diff
@@ -94,8 +94,22 @@ impl QuantumTensor {
...
     fn __dlpack_device__(&self) -> PyResult<(i32, i32)> {
-        // DLDeviceType::kDLCUDA = 2, device_id = 0
-        Ok((2, 0))
+        if self.ptr.is_null() {
+            return Err(PyRuntimeError::new_err("Invalid DLPack tensor pointer"));
+        }
+
+        unsafe {
+            // Read device_id from DLPack tensor metadata
+            // DLDeviceType::kDLCUDA = 2 (from dlpack.h)
```
Comment (machichima) [inline qdp/qdp-python/src/lib.rs]: nit: remove? Seems duplicated with following comments

File: qdp/qdp-python/src/lib.rs [hunk 3]
```diff
@@ -94,8 +94,22 @@ impl QuantumTensor {
...
     ///     Tuple of (device_type, device_id) where device_type=2 for CUDA
     fn __dlpack_device__(&self) -> PyResult<(i32, i32)> {
-        // DLDeviceType::kDLCUDA = 2, device_id = 0
-        Ok((2, 0))
+        if self.ptr.is_null() {
+            return Err(PyRuntimeError::new_err("Invalid DLPack tensor pointer"));
+        }
+
+        unsafe {
+            // Read device_id from DLPack tensor metadata
```
Comment (machichima) [inline qdp/qdp-python/src/lib.rs]: Maybe we can put // Read device_id from DLPack tensor metadata above line 111, where we actually read the devince_id

File: qdp/qdp-python/src/lib.rs (hunk 1 above)
Comment (rich7420) [reply qdp/qdp-python/src/lib.rs:104]: sure!

File: qdp/qdp-python/src/lib.rs (hunk 2 above)
Comment (rich7420) [reply qdp/qdp-python/src/lib.rs]: oh my mistake , thanks!

File: qdp/qdp-python/src/lib.rs (hunk 3 above)
Comment (rich7420) [reply qdp/qdp-python/src/lib.rs]: sure!

**Comment by rich7420** [comment]
@machichima thanks for the review!

File: qdp/qdp-python/tests/test_bindings.py [hunk 4]
```diff
@@ -50,6 +50,36 @@ def test_dlpack_device():
...
+@pytest.mark.gpu
+def test_dlpack_device_id_non_zero():
+    """Test device_id propagation for non-zero devices (requires multi-GPU)."""
+    pytest.importorskip("torch")
+    import torch
+    from mahout_qdp import QdpEngine
+
+    # Check if multiple GPUs are available
+    if not torch.cuda.is_available() or torch.cuda.device_count() < 2:
+        pytest.skip("Multi-GPU setup required for this test")
```
Comment (machichima) [inline qdp/qdp-python/tests/test_bindings.py]: nit: It's better to use `pytest.mark.skipif` to skip before any setup runs and make it clearer that the test is skipped in the first glance

```py
@pytest.mark.skipif(
    not __import__("torch").cuda.is_available() or __import__("torch").cuda.device_count() < 2,
    reason="Multi-GPU setup required for this test"
)
```

**Comment by rich7420** [comment]
@machichima , @ryankert01 thanks for the review !
