### PR TITLE
[QDP] fix test bug

### LINKED ISSUE #733: [QDP] [Bug] fix test bug
### Description
Related to #712 
default is f32, so the bits result would be 32*2=64
solution: Make the test not init the executor to default, instead init to a predetermined f64

### PR DESCRIPTION
**Pull request by ryankert01**
### Purpose of PR

default has been changed to f32, so the bits result would be 32*2=64
solution: Make the test not init the executor to default, instead init to a predetermined f64
### Related Issues or PRs
Closes #733 

### Changes Made

- [ ] Bug fix
- [ ] New feature
- [ ] Refactoring
- [ ] Documentation
- [ ] Test
- [ ] CI/CD pipeline
- [ ] Other

### Breaking Changes

- [ ] Yes
- [ ] No

### Checklist

- [ ] Added or updated unit tests for all changes
- [ ] Added or updated documentation for all changes
- [ ] Successfully built and ran all unit tests or manual tests locally
- [ ] PR title follows "MAHOUT-XXX: Brief Description" format (if related to an issue)
- [ ] Code follows ASF guidelines

## TODO

- [ ] add a test for original `new()` fp32, bring back the coverage

### CODE REVIEW

File: qdp/qdp-core/tests/memory_safety.rs [hunk 1]
```diff
@@ -114,15 +118,24 @@ fn test_dlpack_tensor_metadata() {
         assert_eq!(stride, 1, "Stride for 1D contiguous array should be 1");
 
         assert_eq!(tensor.dtype.code, 5, "Should be complex type (code=5)");
-        assert_eq!(tensor.dtype.bits, 128, "Should be 128 bits (2x64-bit floats)");
+        assert_eq!(
+            tensor.dtype.bits, 128,
+            "Should be 128 bits (2x64-bit floats)"
+        );
```
Comment (ryankert01) [inline qdp/qdp-core/tests/memory_safety.rs:172]: this is the failed test

File: qdp/qdp-core/tests/memory_safety.rs [hunk 2]
```diff
@@ -90,7 +94,7 @@ fn test_multiple_concurrent_states() {
 fn test_dlpack_tensor_metadata() {
     println!("Testing DLPack tensor metadata...");
 
-    let engine = match QdpEngine::new(0) {
+    let engine = match QdpEngine::new_with_precision(0, Precision::Float64) {
```
Comment (ryankert01) [inline qdp/qdp-core/tests/memory_safety.rs:145]: This is what I changed

**Comment by 400Ping** [comment]
Can you provide the reproduction scrip you run for the error?

**Comment by ryankert01** [comment]
> Can you provide the reproduction scrip you run for the error?

cargo test

**Comment by 400Ping** [comment]
strange, my local test passed.

**Comment by ryankert01** [comment]
@400Ping As I'm concerned, there's a PR change default from fp64 to fp32 
Correct me if I'm wrong

**Comment by machichima** [comment]
I can reproduce the error on the newest `dev-qdp` branch

image

File: qdp/qdp-core/tests/memory_safety.rs (hunk 1 above)
Comment (machichima) [reply qdp/qdp-core/tests/memory_safety.rs:172]: I am thinking as we change the precision to float32 by default, should we set the expected value to 2x32 rather than change the precision back to float64?

Comment (400Ping) [reply qdp/qdp-core/tests/memory_safety.rs:172]: see [this](https://github.com/apache/mahout/pull/739), working on float32 right now.

**Comment by 400Ping** [comment]
> @400Ping As I'm concerned, there's a PR change default from fp64 to fp32 Correct me if I'm wrong

Yes, I am also working on the follow up as well.

**Comment by ryankert01** [comment]
cc @guan404ming @rich7420

**Comment by rich7420** [comment]
local test all passed.
