### PR TITLE
[QDP] Enhance numerical safety checks in preprocessor

### LINKED ISSUE #804: [Bug] `NaN` and `Infinity` Propagation may cause numerical safety issue
### Description

The preprocessing pipeline in `qdp-core` did not validate input data for NaN (Not a Number) and Infinity values, allowing invalid numerical values to propagate through the quantum encoding pipeline.

### Steps to Reproduce

Writing a script to reproduce it:

```rust
use qdp_core::preprocessing::Preprocessor;

// This would pass validation and return NaN
let data_with_nan = vec![1.0, f64::NAN, 3.0];
let result = Preprocessor::calculate_l2_norm(&data_with_nan);
// Result: Ok(NaN)
```

### Expected Behavior

All preprocessing functions should return `Err(MahoutError::InvalidInput)` with clear error messages when NaN or Infinity values are detected.

### Actual Behavior

When input data contains NaN or Infinity values:
- `validate_input()` and `validate_batch()` would pass validation
- `calculate_l2_norm()` and `calculate_batch_l2_norms()` would return NaN/Infinity
- These invalid values would propagate to quantum simulation, causing:
  - Invalid quantum state vectors
  - GPU computation errors
  - Silent failures or crashes

### Environment
- In every environment

### Additional Context
I'm willing to help to solve the issue! 🙌

### PR DESCRIPTION
**Pull request by viiccwen**
### Purpose of PR
1. Added validation for NaN and Infinity values in input data and L2 norm calculations.
2. Updated correlated tests to cover these scenarios.

### Related Issues or PRs
resolve #804 

### Changes Made

- [x] Bug fix
- [ ] New feature
- [ ] Refactoring
- [ ] Documentation
- [x] Test
- [ ] CI/CD pipeline
- [ ] Other

### Breaking Changes

- [ ] Yes
- [x] No

### Checklist

- [x] Added or updated unit tests for all changes
- [ ] Added or updated documentation for all changes
- [x] Successfully built and ran all unit tests or manual tests locally
- [x] PR title follows "MAHOUT-XXX: Brief Description" format (if related to an issue)
- [x] Code follows ASF guidelines

### CODE REVIEW

**Comment by ryankert01** [comment]
To my knowledge, pennylane do not validate, although it's a nice-to-have. It's a O(N), so I will suggest we do it later than benchmarking.

**Comment by viiccwen** [comment]
Sure, what if we enable it only in dev environment? 🤔
we get strict validation during development, but it compiles away to a zero-cost op in release builds.

**Comment by ryankert01** [comment]
Not sure if we have a release build, but validate norm is O(1), so I think we can have that! Not sure how it should be done though. 
Let me cc a quantum guy @rich7420

**Comment by viiccwen** [comment]
Thx! 🙌

**Comment by rich7420** [comment]
thanks for the patch @viiccwen !
Doing validate_input and then calculate_l2_norm in debug mode is basically two full O(N) passes. Once you get into ~20+ qubits, that can definitely make local runs feel sluggish.
I think we could do with the IEEE 754 behavior approach: NaNs/Infs will naturally "poison" the sum during the norm calculation, so you're already getting most of that validation for free:

- Any NaN in the input → sum of squares becomes NaN
- Any Inf in the input → sum becomes Inf

So yeah, in most cases we can drop the separate check_numerical_safety loop and just rely on the end-of-calculate_l2_norm guard (lines 86–96) to catch:

1. Invalid inputs (NaN/Inf)
2. Overflow during accumulation

That gives you a single O(N) pass, keeps things cleaner, and speeds up debug builds without affecting release.
WDYT?

**Comment by viiccwen** [comment]
> thanks for the patch @viiccwen ! Doing validate_input and then calculate_l2_norm in debug mode is basically two full O(N) passes. Once you get into ~20+ qubits, that can definitely make local runs feel sluggish. I think we could do with the IEEE 754 behavior approach: NaNs/Infs will naturally "poison" the sum during the norm calculation, so you're already getting most of that validation for free:
> 
> * Any NaN in the input → sum of squares becomes NaN
> * Any Inf in the input → sum becomes Inf
> 
> So yeah, in most cases we can drop the separate check_numerical_safety loop and just rely on the end-of-calculate_l2_norm guard (lines 86–96) to catch:
> 
> 1. Invalid inputs (NaN/Inf)
> 2. Overflow during accumulation
> 
> That gives you a single O(N) pass, keeps things cleaner, and speeds up debug builds without affecting release. WDYT?

Agree. I hadn’t considered IEEE 754 propagation behavior. It'll be removed later.
And also agree to keep the nan/inf guard, although we've checked nan/inf situation later stages:

https://github.com/apache/mahout/blob/bff0b88ef38808263a65a24a8d2ee2352bd0e1b4/qdp/qdp-kernels/src/amplitude.cu#L147-L149

It should help catch invalid values early in the pipeline as well : ) 
Thanks for the suggestion!

**Comment by viiccwen** [comment]
@ryankert01 Thx for pointing that out, and apologies for not discussing this first before opening the PR.

Sure, even if we don’t have a clear release/debug distinction here, an O(1) validation step could still make sense.
I should have raised this for discussion earlier instead of jumping straight into an implementation.

I’ll make sure to bring these kinds of changes up for discussion first and avoid wasting others time : ) 
Thanks again for the feedback!

File: qdp/qdp-core/tests/preprocessing.rs [hunk 1]
```diff
@@ -53,8 +53,8 @@ fn test_validate_input_empty_data() {
 
 #[test]
 fn test_validate_input_data_too_large() {
-    let data = vec![1.0, 0.0, 0.0]; // 3 elements
-    let result = Preprocessor::validate_input(&data, 1); // max size 2^1 = 2
+    let data = vec![1.0, 0.0, 0.0];
+    let result = Preprocessor::validate_input(&data, 1);
```
Comment (ryankert01) [inline qdp/qdp-core/tests/preprocessing.rs]: whats the reason of removing comments?

File: qdp/qdp-core/tests/preprocessing.rs [hunk 2]
```diff
@@ -63,7 +63,7 @@ fn test_validate_input_data_too_large() {
 #[test]
 fn test_validate_input_allows_partial_state() {
     let data = vec![0.5, -0.5, 0.25];
-    assert!(Preprocessor::validate_input(&data, 3).is_ok()); // state vector can hold up to 8 elements
+    assert!(Preprocessor::validate_input(&data, 3).is_ok());
```
Comment (ryankert01) [inline qdp/qdp-core/tests/preprocessing.rs]: ditto.

File: qdp/qdp-core/tests/preprocessing.rs [hunk 3]
```diff
@@ -105,3 +105,48 @@ fn test_calculate_l2_norm_matches_sequential_sum() {
...
+    }
+}
+
+#[test]
+fn test_calculate_batch_l2_norms_success() {
+    let batch_data = vec![3.0, 4.0, 5.0, 12.0];
+    let norms = Preprocessor::calculate_batch_l2_norms(&batch_data, 2, 2).unwrap();
+    assert_eq!(norms.len(), 2);
+    assert!((norms[0] - 5.0).abs() < 1e-10); // sqrt(3^2 + 4^2) = 5
+    assert!((norms[1] - 13.0).abs() < 1e-10); // sqrt(5^2 + 12^2) = 13
```
Comment (ryankert01) [inline qdp/qdp-core/tests/preprocessing.rs]: nit: although completely understand what its doing, we can also use `approx::assert_relative_eq` to enhance its readability.

**Review by ryankert01 — COMMENTED** [review]
some nits

File: qdp/qdp-core/tests/preprocessing.rs (hunk 3 above)
Comment (viiccwen) [reply qdp/qdp-core/tests/preprocessing.rs]: Thx for the suggestion!

I followed the existing pattern used earlier in the code, but I agree that using `approx::assert_relative_eq` would improve readability. 
I’ll add `approx` as a dev-dependency and update the tests accordingly.

File: qdp/qdp-core/tests/preprocessing.rs (hunk 1 above)
Comment (viiccwen) [reply qdp/qdp-core/tests/preprocessing.rs]: thx for pointing out. I'll undo it later.

File: qdp/qdp-core/tests/preprocessing.rs (hunk 2 above)
Comment (viiccwen) [reply qdp/qdp-core/tests/preprocessing.rs]: thx for pointing out. I'll undo it later.
